server:
  port: 8990
spring:
   application:
     name: API-GATEWAY
   cloud:
    gateway:
      routes:
        - id: COMPOSITE-SERVICE
          uri: lb://COMPOSITE-SERVICE
          predicates:
            - Path=/api/shoppingservice/**
          filters:
            - name: CircuitBreaker
              args:
                name: COMPOSITE-SERVICE
                fallbackuri: forward:/shoppingservicefallback
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: CUSTOMER-SERVICE
                fallbackuri: forward:/customerservicefallback
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productservicefallback
        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          filters:
            - name: CircuitBreaker
              args:
                name: INVENTORY-SERVICE
                fallbackuri: forward:/inventoryservicefallback
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart/**
          filters:
            - name: CircuitBreaker
              args:
                name: CART-SERVICE
                fallbackuri: forward:/cartservicefallback
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderservicefallback
        
         
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000   
   
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/ 
  instance: 
    hostname: localhost
  
